// Code generated by 'go generate'; DO NOT EDIT.

package winiphlpapi

import (
	"syscall"
	"unsafe"

	"golang.org/x/sys/windows"
)

var _ unsafe.Pointer

// Do the interface allocations only once for common
// Errno values.
const (
	errnoERROR_IO_PENDING = 997
)

var (
	errERROR_IO_PENDING error = syscall.Errno(errnoERROR_IO_PENDING)
	errERROR_EINVAL     error = syscall.EINVAL
)

// errnoErr returns common boxed Errno values, to prevent
// allocations at runtime.
func errnoErr(e syscall.Errno) error {
	switch e {
	case 0:
		return errERROR_EINVAL
	case errnoERROR_IO_PENDING:
		return errERROR_IO_PENDING
	}
	// TODO: add more here, after collecting data on the common
	// error values see on Windows. (perhaps when running
	// all.bat?)
	return e
}

var (
	modadvapi32 = windows.NewLazySystemDLL("advapi32.dll")
	modiphlpapi = windows.NewLazySystemDLL("iphlpapi.dll")

	procI_QueryTagInformation       = modadvapi32.NewProc("I_QueryTagInformation")
	procGetExtendedTcpTable         = modiphlpapi.NewProc("GetExtendedTcpTable")
	procGetExtendedUdpTable         = modiphlpapi.NewProc("GetExtendedUdpTable")
	procGetOwnerModuleFromTcp6Entry = modiphlpapi.NewProc("GetOwnerModuleFromTcp6Entry")
	procGetOwnerModuleFromTcpEntry  = modiphlpapi.NewProc("GetOwnerModuleFromTcpEntry")
	procGetOwnerModuleFromUdp6Entry = modiphlpapi.NewProc("GetOwnerModuleFromUdp6Entry")
	procGetOwnerModuleFromUdpEntry  = modiphlpapi.NewProc("GetOwnerModuleFromUdpEntry")
	procGetPerTcp6ConnectionEStats  = modiphlpapi.NewProc("GetPerTcp6ConnectionEStats")
	procGetPerTcpConnectionEStats   = modiphlpapi.NewProc("GetPerTcpConnectionEStats")
	procGetTcp6Table                = modiphlpapi.NewProc("GetTcp6Table")
	procGetTcpTable                 = modiphlpapi.NewProc("GetTcpTable")
	procSetPerTcp6ConnectionEStats  = modiphlpapi.NewProc("SetPerTcp6ConnectionEStats")
	procSetPerTcpConnectionEStats   = modiphlpapi.NewProc("SetPerTcpConnectionEStats")
)

func queryTagInformation(machineName *uint16, infoLevel uint32, tagInfo unsafe.Pointer) (errcode error) {
	r0, _, _ := syscall.SyscallN(procI_QueryTagInformation.Addr(), uintptr(unsafe.Pointer(machineName)), uintptr(infoLevel), uintptr(tagInfo))
	if r0 != 0 {
		errcode = syscall.Errno(r0)
	}
	return
}

func getExtendedTcpTable(pTcpTable *byte, pdwSize *uint32, bOrder bool, ulAf uint64, tableClass uint32, reserved uint64) (errcode error) {
	var _p0 uint32
	if bOrder {
		_p0 = 1
	}
	r0, _, _ := syscall.SyscallN(procGetExtendedTcpTable.Addr(), uintptr(unsafe.Pointer(pTcpTable)), uintptr(unsafe.Pointer(pdwSize)), uintptr(_p0), uintptr(ulAf), uintptr(tableClass), uintptr(reserved))
	if r0 != 0 {
		errcode = syscall.Errno(r0)
	}
	return
}

func getExtendedUdpTable(pUdpTable *byte, pdwSize *uint32, bOrder bool, ulAf uint64, tableClass uint32, reserved uint64) (errcode error) {
	var _p0 uint32
	if bOrder {
		_p0 = 1
	}
	r0, _, _ := syscall.SyscallN(procGetExtendedUdpTable.Addr(), uintptr(unsafe.Pointer(pUdpTable)), uintptr(unsafe.Pointer(pdwSize)), uintptr(_p0), uintptr(ulAf), uintptr(tableClass), uintptr(reserved))
	if r0 != 0 {
		errcode = syscall.Errno(r0)
	}
	return
}

func getOwnerModuleFromTcp6Entry(pTcpEntry *MibTcp6RowOwnerModule, class uint32, pBuffer *byte, pdwSize *uint32) (errcode error) {
	r0, _, _ := syscall.SyscallN(procGetOwnerModuleFromTcp6Entry.Addr(), uintptr(unsafe.Pointer(pTcpEntry)), uintptr(class), uintptr(unsafe.Pointer(pBuffer)), uintptr(unsafe.Pointer(pdwSize)))
	if r0 != 0 {
		errcode = syscall.Errno(r0)
	}
	return
}

func getOwnerModuleFromTcpEntry(pTcpEntry *MibTcpRowOwnerModule, class uint32, pBuffer *byte, pdwSize *uint32) (errcode error) {
	r0, _, _ := syscall.SyscallN(procGetOwnerModuleFromTcpEntry.Addr(), uintptr(unsafe.Pointer(pTcpEntry)), uintptr(class), uintptr(unsafe.Pointer(pBuffer)), uintptr(unsafe.Pointer(pdwSize)))
	if r0 != 0 {
		errcode = syscall.Errno(r0)
	}
	return
}

func getOwnerModuleFromUdp6Entry(pUdpEntry *MibUdp6RowOwnerModule, class uint32, pBuffer *byte, pdwSize *uint32) (errcode error) {
	r0, _, _ := syscall.SyscallN(procGetOwnerModuleFromUdp6Entry.Addr(), uintptr(unsafe.Pointer(pUdpEntry)), uintptr(class), uintptr(unsafe.Pointer(pBuffer)), uintptr(unsafe.Pointer(pdwSize)))
	if r0 != 0 {
		errcode = syscall.Errno(r0)
	}
	return
}

func getOwnerModuleFromUdpEntry(pUdpEntry *MibUdpRowOwnerModule, class uint32, pBuffer *byte, pdwSize *uint32) (errcode error) {
	r0, _, _ := syscall.SyscallN(procGetOwnerModuleFromUdpEntry.Addr(), uintptr(unsafe.Pointer(pUdpEntry)), uintptr(class), uintptr(unsafe.Pointer(pBuffer)), uintptr(unsafe.Pointer(pdwSize)))
	if r0 != 0 {
		errcode = syscall.Errno(r0)
	}
	return
}

func getPerTcp6ConnectionEStats(row *MibTcp6Row, estatsType uint32, rw uintptr, rwVersion uint64, rwSize uint64, ros uintptr, rosVersion uint64, rosSize uint64, rod uintptr, rodVersion uint64, rodSize uint64) (errcode error) {
	r0, _, _ := syscall.SyscallN(procGetPerTcp6ConnectionEStats.Addr(), uintptr(unsafe.Pointer(row)), uintptr(estatsType), uintptr(rw), uintptr(rwVersion), uintptr(rwSize), uintptr(ros), uintptr(rosVersion), uintptr(rosSize), uintptr(rod), uintptr(rodVersion), uintptr(rodSize))
	if r0 != 0 {
		errcode = syscall.Errno(r0)
	}
	return
}

func getPerTcpConnectionEStats(row *MibTcpRow, estatsType uint32, rw uintptr, rwVersion uint64, rwSize uint64, ros uintptr, rosVersion uint64, rosSize uint64, rod uintptr, rodVersion uint64, rodSize uint64) (errcode error) {
	r0, _, _ := syscall.SyscallN(procGetPerTcpConnectionEStats.Addr(), uintptr(unsafe.Pointer(row)), uintptr(estatsType), uintptr(rw), uintptr(rwVersion), uintptr(rwSize), uintptr(ros), uintptr(rosVersion), uintptr(rosSize), uintptr(rod), uintptr(rodVersion), uintptr(rodSize))
	if r0 != 0 {
		errcode = syscall.Errno(r0)
	}
	return
}

func getTcp6Table(tcpTable *byte, sizePointer *uint32, order bool) (errcode error) {
	var _p0 uint32
	if order {
		_p0 = 1
	}
	r0, _, _ := syscall.SyscallN(procGetTcp6Table.Addr(), uintptr(unsafe.Pointer(tcpTable)), uintptr(unsafe.Pointer(sizePointer)), uintptr(_p0))
	if r0 != 0 {
		errcode = syscall.Errno(r0)
	}
	return
}

func getTcpTable(tcpTable *byte, sizePointer *uint32, order bool) (errcode error) {
	var _p0 uint32
	if order {
		_p0 = 1
	}
	r0, _, _ := syscall.SyscallN(procGetTcpTable.Addr(), uintptr(unsafe.Pointer(tcpTable)), uintptr(unsafe.Pointer(sizePointer)), uintptr(_p0))
	if r0 != 0 {
		errcode = syscall.Errno(r0)
	}
	return
}

func setPerTcp6ConnectionEStats(row *MibTcp6Row, estatsType uint32, rw uintptr, rwVersion uint64, rwSize uint64, offset uint64) (errcode error) {
	r0, _, _ := syscall.SyscallN(procSetPerTcp6ConnectionEStats.Addr(), uintptr(unsafe.Pointer(row)), uintptr(estatsType), uintptr(rw), uintptr(rwVersion), uintptr(rwSize), uintptr(offset))
	if r0 != 0 {
		errcode = syscall.Errno(r0)
	}
	return
}

func setPerTcpConnectionEStats(row *MibTcpRow, estatsType uint32, rw uintptr, rwVersion uint64, rwSize uint64, offset uint64) (errcode error) {
	r0, _, _ := syscall.SyscallN(procSetPerTcpConnectionEStats.Addr(), uintptr(unsafe.Pointer(row)), uintptr(estatsType), uintptr(rw), uintptr(rwVersion), uintptr(rwSize), uintptr(offset))
	if r0 != 0 {
		errcode = syscall.Errno(r0)
	}
	return
}
